tpoechtrager/osxcross

README.md

Hi,
This PR adds a reference to [multiarch/crossbuild](https://github.com/multiarch/crossbuild) in the README.md.

Add a reference to multiarch/crossbuild

---

tools/osxcross-macports

Some packages (such as the qt5 metapackage) are not architecture-specific - "noarch" versions should work on all architectures.

Let osxcross-macports pick up noarch packages

---

build.sh
patches/cctools-ld64-3.patch

One behavior of cctools' libtool when invoked as ranlib is rotating archives of universal object files (such as those created by `clang -arch i386 -arch x86_64 -c ...`) into universal files containing per-architecture archives each containing single-architecture objects. From Xcode 7 until Xcode 7.3, whose cctools/ld64 are not yet open source, there was a bug where this would fail if any of the individual objects were LLVM bitcode objects rather than natively compiled ones, and incorrectly succeed with nonsensical results if such an archive contained members that were not recognizable object files at all. The fix is straightforward and this commit adds a patch to apply it while we wait for newer cctools sources to be released.
(This might be a bit of a trivial obsessive pet peeve, but …

Add patch for ranlib bug not yet fixed in cctools 877.8

---

README.md

Notes from Thomas Pöchtrager:
* The *-g++-libc++ aliases use the Clang C++ library.
* Don't use the Clang C++ library with GCC.
* You can use an installed Clang, or build your own.
* Same Clang serves both to compile OSXCross and as the cross-compiler.
* INSTALLPREFIX is specifically for installing a (native!) clang.
Other tweaks to the text:
* Broke some lines before 80 characters (found by lint check).
* Removed some trailing spaces (found by lint check).
* Put shell commands on their own, indendent lines.
* Explain GCC_VERSION, ENABLE_FORTRAN, etc. explicitly.
* Make each footnote its own paragraph, on a separate line.
* Minor tweaks to wording for style & idiom.

Notes based on Thomas' email, and text tweaks.

---

tools/gen_sdk_package_darling_dmg.sh

I'm using Kubuntu 16.04 and it seems that fuse has been built into kernel. I can no more find the package `fuse-utils` in repository.
Not sure since when it's been in the kernel... but better to let users handle it?

skip fuse module check in ubuntu

---

wrapper/main.cpp
wrapper/target.cpp
wrapper/target.h

In some environments you can't rely on the compiler's location being on the path, or you want a specific version of clang to be used.
With the `-foc-compiler-path=<location>` command line switch you can specify the compiler's path and osxcross will not attempt to look in the PATH for it.

Added functionality to have clang in a custom directory, and not in the PATH

---

README.md
tools/gen_sdk_package_darling_dmg.sh

This pulls in the https://github.com/darlinghq/darling-dmg/pull/41 fix
for compilation with newer GCC.
The error message this fixes is
```
osxcross/build/darling-dmg/src/main-fuse.cpp:137:28: error: no member named 'function' in namespace 'std'
int handle_exceptions(std::function<int()> func)
~~~~~^
osxcross/build/darling-dmg/src/main-fuse.cpp:137:44: error: use of undeclared identifier 'func'
int handle_exceptions(std::function<int()> func)
^
osxcross/build/darling-dmg/src/main-fuse.cpp:137:49: error: expected ';' after top level declarator
int handle_exceptions(std::function<int()> func)
^
;
3 errors generated.
```

 Fix compilation issue in `darling-dmg`

---

tools/get_dependencies.sh

This script handles the fact that uuid is not available on Arch Linux package manager (pacman). It is instead downloaded and built from AUR using makepkg.
A possible limitation would be that if the target machine has multiple users, this line might not get the one you want... In that case, maybe you could enter the user you want in the variable definition.
Replace :
USER="$(cat /etc/passwd | grep '/home' | cut -d: -f1 | head -1)" 
By:
USER="username"

Feature: get_dependencies for Arch linux users

---

wrapper/Makefile
wrapper/programs/osxcross-conf.cpp

With C++14 the following error happens on CentOS 7.x:
```
$ clang++ -std=c++1y -Wall -Wextra -pedantic -Wno-missing-field-initializers \
-I. -O2 -DOSXCROSS_VERSION="\"1.2\"" -DOSXCROSS_TARGET="\"darwin14\"" \
-DOSXCROSS_OSX_VERSION_MIN="\"10.6\"" -DOSXCROSS_LINKER_VERSION="\"530\"" \
-DOSXCROSS_LIBLTO_PATH="\"/usr/lib64/llvm\"" \
-DOSXCROSS_BUILD_DIR="\"/osxcross/build\""  -isystem quirks/include \
-c -o target.o target.cpp
In file included from target.cpp:24:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/iostream:39:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ostream:38:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ios:42:
In file …
```

Fix building on CentOS 7.x

---

build_gcc.sh

There're quite a few mirrors where GNU software might be found. Though there're some problems with them:
1. There's no guarantee any random mirror will be still up tomorrow
2. For mere mortal it's not clear how credible if https://xxx-yyy-zzz.org in a sense that either tarball with sources might be corrupted
unintentionally or even with some bad intentions.
One solution here might be calculation of checksum but still as long as the main "FTP" storage of GNU project is up there's     not much sense in using a _hard-coded_ mirror.
Unfortunately snapshots of GCC are not hosted at https://ftp.gnu.org/, so keeping https://mirror.koddos.net for now.

Use official GNU download area

---

build_clang.sh

It looks like `https://releases.llvm.org` does not provide the LLVM and Clang releases anymore.
The website points to Gihub in its Download section.
Update the `build_clang.sh` script to download tarballs from new location.

Update download location and filename for LLVM and Clang source tarballs

---

build_clang.sh

To get a completely env independent setup we may want to install Clang/LLVM to the target folder as well. So let's allow user to do it in a scripted way just adding `ENABLE_CLANG_INSTALL=1` for execution string.

build_clang.sh: Allow unmanned instllation

---

README.md
tools/gen_sdk_package_tools.sh
tools/gen_sdk_package_tools_dmg.sh

Being able to extract SDKs from Command Line Tools for Xcode instead of the full Xcode package saves bandwidth, disk space, and time.
Two scripts are added:
* `tools/gen_sdk_package_tools.sh`: extracts SDKs from installed Command Line Tools on macOS (`/Library/Developer/CommandLineTools`) or from a path specified via `XCODE_TOOLS_DIR`
* `tools/gen_sdk_package_tools_dmg.sh`: unpacks the content of provided `Command_Line_Tools_for_Xcode.dmg` and extracts SDKs via the above script.
Tested with Command Line Tools for Xcode 12.x.

Add scripts for extracting SDKs from Command Line Tools for Xcode

---

tools/tools.sh

Move setting build_complete_file to after fetching project_name using
get_project_name_from_url. Avoids empty ".FOO_build_complete" file name.
* Fix up a number of shellcheck issues in get_sources().
Signed-off-by: Ben Kochie <superq@gmail.com>

Fix build_complete_file in get_sources

---

tools/tools.sh

As OpenSSL is expected to be in a standard UNIX location but that's not always the case on macOS, this works around the issue regardless of package manager used as long as pkg-config is installed into $PATH
Macports default prefix is /opt/local
Homebrew on M1 uses /opt/homebrew
I'm sure there's a better way to handle this but if `pkg-config` is listed as a requirement this solves finding the dependencies without patches sources like xar.

tools.sh: Workaround hardcoded paths

---

tools/tools.sh

This PR updates the exit code for `verify_sdk_version` to `1` function if the SDK is not found.
This should help to stop the build in automatic scripts when the `SDK_VERSION` env variable is set to a invalid value.

verify_sdk_version: exit with code 1 if the SDK is not found

---

README.md

I tried to follow the instructions outlined in PACKAGING THE SDK,
and as it turns out the instructions for Linux required more than
40GB of disk space. That's why I think it would be best to tell
readers that they might need up to 45GB of space rather than
up to 25GB. I'm not sure if the instructions are simply outdated
in this regard or if the space requirements are just different for
other reasons, however I highly suspect the former to be the case.

Increase maximum disk space required for packaging SDK

---

README.COMPILER-RT.md
README.md
build_compiler_rt.sh

Also mention that compiler-rt can be needed to build code using
`__builtin_available()`.
Fixes #278.
Note: Draft as I'm still testing it to see if it actually works as expected.
*Edit:* Tested OK with `USE_CMAKE=1` and LLVM 12 on Fedora 34.

compiler-rt: Add option to automate install process

---

tools/osxcross-macports

This adds support to use arm64 packages on macports. Especially useful for external libraries.

added arm64 switch to osxcross-macports

---

tools/osxcross-macports

Workaround to deal with upgraded-then-downgraded macports ports.
When getting package url, get current version number from ports.macports.org then grep for the right version.

osxcross-macports: add package version check

---

build_clang.sh

Update tarball download location to Github to accommodate new download site format (introduced in version 11.0.1, but works for all versions).
Fixes #303. (see issue for further description)

Update tarball download location to Github

---

build_compiler_rt.sh

This PR fixes an issue with compiler-rt 13.x by disabling standard LLVM include dirs for lib/orc project.
Closes #308.

Fix for compiler-rt 13.x build

---

tools/osxcross-cmake

Since cmake 3.20, "-D" prevents any build options (--build, --target, -j,
etc) from working. It will abort with an "unrecognized argument" error.
Fix the issue by passing the toolchain file as an env variable to cmake,
not with -D.

Fix cmake wrapper breaking cmake build options

---

tools/gen_sdk_package_tools_dmg.sh

This PR allows to extract the Command Line Tools pkg with a not standard name from the .dmg.
For example `Command_Line_Tools_macOS_10.11_for_Xcode_8.2.dmg` contains `Command Line Tools (macOS El Capitan version 10.11).pkg` and the `Command_Line_Tools_OS_X_10.11_for_Xcode_7.3.dmg` contains `Command Line Tools (OS X 10.11).pkg` instead of `Command Line Tools.pkg`

gen_sdk_package_tools_dmg: extract packages with not standard name

---

tools/gen_sdk_package.sh

I was using an older version of this script and eventually it stopped working because it was only designed to work for macOS version 10, and didn't anticipate version 11 or 12 being released.
In order to prevent that from happening again in a year or two, this pull request removes the hardcoded version numbers and uses a more general regular expression to find SDKs.  Additionally, I fixed it so that an error message is shown if no SDKs are found, which was the original intent of the code.

Make gen_sdk_package.sh better at finding SDKs

---

build_compiler_rt.sh

This fixes build with Clang 14.0 on Fedora 36, and might enable building
against in-dev Clang 15, but I haven't tested it.
Fixes #340.

compiler_rt: Switch Clang 14 version to release/14.x since it's stable

---

build_binutils.sh

GCC doesn't yet have support for aarch64 Darwin, but binutils appears to compile just fine.

Support non-x86_64 targets for binutils

---

README.md

Not terribly important but hey i missed those in my container, figured it would help the next person. Also the first commit uses the name of Debian packages instead of Mageia, because one of the missing dependencies was a `-dev`.

Add some missing dependencies to the list in the README

---

build_clang.sh

Clang was always installed to /usr/local regardless of the INSTALLPREFIX environment variable

Correctly set install prefix for clang

---

README.PPC-GCC-5.5.0-SDK-10.5.md
build_gcc.sh
test_autotools.sh
test_simple.sh

Some minor changes to the build_gcc.sh script to get mainline GCC-5.5.0 working with the ppc-test branch.
Also documentation describing how I created a usable toolchain that seems to be working flawlessly. It can build C and C++ up C++14 code that runs on my iBook G4.
The toolchain also builds for PowerPC64, although I am unable to test, since I dont have access to a PowerPC64 Mac at this time.
I have provided a couple of scripts:
test_autotools.sh: Builds the latest version of OpenSSL, WGet, and CURL and they are running and working on my iBook G4.
test_simple.sh: Builds some F77, F90, C89, C11, C++03, C++11, and C++14 programs that run on my iBook G4. Well except for the Fortran programs because the OS X Cross build did not stage the gfortran compiler for PPC32.
Please consider merging …

Usable OS X Cross PPC Toolchain with Mainline GCC-5.5.0

---

build_compiler_rt.sh

This tiny fix resolves the issue when build_compiler_rt.sh silently fails without any messages whatsoever if the `build` directory is cleaned up.

Make sure $BUILD_DIR exists before building compiler-rt

---

tools/toolchain.cmake

This enables the use of -DCMAKE_FIND_ROOT_PATH=/additional/root/path.
This is useful when building with dependencies that are built separately and is available in different root path.
This probably also solves: https://github.com/tpoechtrager/osxcross/issues/241
There is discussion about the use case here: https://discourse.cmake.org/t/cmake-find-root-path-and-toolchain-files/3294/3

fix: don't overwrite CMAKE_FIND_ROOT_PATH

---

tools/gen_sdk_package_tools_dmg.sh

This PR removes the usage of `cpio -D` in order to support older versions. Ubuntu 16.04 has `cpio` version 2.11, which does not contain the `-D` argument.

Use `cd` instead of `cpio -D` to support older versions of `cpio`

---

CHANGELOG
README.MACPORTS.md
README.md
tools/osxcross-macports

I've made the same mistake, it's an easy one to do. Thanks for the project, it's been a life saver!

Fix misnamed "packet manager" to "package manager"  in docs

---

tools/osxcross-macports

like packages: https://packages.macports.org/xorg-xorgproto/
As now **omp** is unable to installs **xorg-xorgproto** as it is marked "`darwin_any.noarch`" and prev check
`$OSXVERSION | grep "noarch"`
never match those kind of packages.
This solve also: https://github.com/tpoechtrager/osxcross/issues/399

tools/osxcross-macports: add support for "any" darwin version

---

wrapper/target.cpp

Due to the install location of clang on Fedora (in /usr/lib64/llvm20 for clang 20 for example) The header search will eventually hit the fallback search for `../include/clang` and find a match, however the directory it finds doesn't include clang headers.
Instead Fedora installs it's clang headers under `/usr/lib/clang/20/include`. This fix ensures that directory is resolved before any of the fallbacks are hit.

Fix detection for intrinsic clang headers on Fedora

---

wrapper/target.cpp

See issue: https://github.com/tpoechtrager/osxcross/issues/463
Simple .cpp file:
~~~
$ cat testCompiler.cpp 
#include <iostream>
int main(void)
{
#ifdef __apple_build_version__
std::cout << "__apple_build_version__ set" << std::endl;
#else
std::cout << "__apple_build_version__ NOT set" << std::endl;
#endif
#ifdef __clang__
std::cout << "__clang__ set" << std::endl;
#else
std::cout << "__clang__ NOT set" << std::endl;
#endif
}
~~~
Run command:
~~~
/usr/local/osxcross/bin/aarch64-apple-darwin20.2-clang++ -E testCompiler.cpp
~~~
Check result:
~~~
std::cout << "__apple_build_version__ NOT set" << std::endl;
~~~
Then run:
~~~
export OSXCROSS_PRETEND_TO_BE_APPLE_CLANG=1
/usr/local/osxcross/bin/aarch64-apple-darwin20.2-clang++ -E testCompiler.cpp
~~~
Check result:
~~~
std::cout << …

Allow __apple_build_version__ exposure from apple-clang wrapper

---

README.md

The command line tools link does not work anymore. Updated it.

fix: dead command line tools link in readme
